PPO_AB_CONTROLLER_ABSOLUTE_PATH="/home/taghianj/Documents/openai/controllers/ppov2/ppov2_ab_controller.py"
RESUME_FILE="/local/melco2-1/shared/fetchreach/normal/PPOv2_FetchReachEnv-v0:6000000_lr:0.000275_lrd:True_g:0.848_ns:3424_mbs:8_epo:24_eps:0.3_c1:1.0_c2:0.0007_cvl:False_mgn:0.5_gae:True_lam:0.9327_hd:64_lstd:0.0_tef:30000_ee:10_tmsf:60000_d:cpu_ps:True_pss:43"
tmux new-session -d -s ppov6-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed0 -d"
tmux new-session -d -s ppov6-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed1 -d"
tmux new-session -d -s ppov6-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed2 -d"
tmux new-session -d -s ppov6-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed3 -d"
tmux new-session -d -s ppov6-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed4 -d"
tmux new-session -d -s ppov6-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed5 -d"
tmux new-session -d -s ppov6-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed6 -d"
tmux new-session -d -s ppov6-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed7 -d"
tmux new-session -d -s ppov6-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed8 -d"
tmux new-session -d -s ppov6-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed9 -d"
tmux new-session -d -s ppov6_cm-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed0 -cm -d"
tmux new-session -d -s ppov6_cm-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed1 -cm -d"
tmux new-session -d -s ppov6_cm-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed2 -cm -d"
tmux new-session -d -s ppov6_cm-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed3 -cm -d"
tmux new-session -d -s ppov6_cm-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed4 -cm -d"
tmux new-session -d -s ppov6_cm-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed5 -cm -d"
tmux new-session -d -s ppov6_cm-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed6 -cm -d"
tmux new-session -d -s ppov6_cm-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed7 -cm -d"
tmux new-session -d -s ppov6_cm-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed8 -cm -d"
tmux new-session -d -s ppov6_cm-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed9 -cm -d"
tmux new-session -d -s ppov6_rn-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed0 -rn -d"
tmux new-session -d -s ppov6_rn-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed1 -rn -d"
tmux new-session -d -s ppov6_rn-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed2 -rn -d"
tmux new-session -d -s ppov6_rn-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed3 -rn -d"
tmux new-session -d -s ppov6_rn-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed4 -rn -d"
tmux new-session -d -s ppov6_rn-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed5 -rn -d"
tmux new-session -d -s ppov6_rn-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed6 -rn -d"
tmux new-session -d -s ppov6_rn-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed7 -rn -d"
tmux new-session -d -s ppov6_rn-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed8 -rn -d"
tmux new-session -d -s ppov6_rn-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed9 -rn -d"
tmux new-session -d -s ppov6_cmrn-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed0 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed1 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed2 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed3 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed4 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed5 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed6 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed7 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed8 -cm -rn -d"
tmux new-session -d -s ppov6_cmrn-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v6 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn -d"
