SAC_N_CONTROLLER_ABSOLUTE_PATH="/home/sschoepp/Documents/openai/controllers/sacv2/sacv2_n_controller.py"
RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.871_t:0.0933_a:0.2_lr:0.002048_hd:256_rbs:1000000_bs:64_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:81_r"
tmux new-session -d -s sac730 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0"
tmux new-session -d -s sac731 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1"
tmux new-session -d -s sac732 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2"
tmux new-session -d -s sac733 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3"
tmux new-session -d -s sac734 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4"
tmux new-session -d -s sac735 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5"
tmux new-session -d -s sac736 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6"
tmux new-session -d -s sac737 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7"
tmux new-session -d -s sac738 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8"
tmux new-session -d -s sac739 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"
