echo 'SAC_N_CONTROLLER_ABSOLUTE_PATH="/home/sschoepp/Documents/openai/controllers/sacv2/sacv2_n_controller.py"' > melco2.sh

# gpu

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9456_t:0.0126_a:0.2_lr:0.00337_hd:256_rbs:1000000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:28_r"' >> melco2.sh
echo 'tmux new-session -d -s sac1 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9455_t:0.0952_a:0.2_lr:0.003612_hd:256_rbs:500000_bs:16_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:36_r"' >> melco2.sh
echo 'tmux new-session -d -s sac2 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9286_t:0.0663_a:0.2_lr:0.002288_hd:256_rbs:1000000_bs:256_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:30_r"' >> melco2.sh
echo 'tmux new-session -d -s sac3 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9096_t:0.0603_a:0.2_lr:0.004293_hd:256_rbs:1000000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:0_r"' >> melco2.sh
echo 'tmux new-session -d -s sac4 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9092_t:0.0821_a:0.2_lr:0.004788_hd:256_rbs:1000000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:39_r"' >> melco2.sh
echo 'tmux new-session -d -s sac5 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh


# cpu

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9299_t:0.0879_a:0.2_lr:0.003035_hd:256_rbs:500000_bs:256_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:18_r"' >> melco2.sh
echo 'tmux new-session -d -s sac6 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.8446_t:0.0551_a:0.2_lr:0.003141_hd:256_rbs:10000_bs:64_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:16_r"' >> melco2.sh
echo 'tmux new-session -d -s sac7 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.8443_t:0.0208_a:0.2_lr:0.005225_hd:256_rbs:10000_bs:64_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:5_r"' >> melco2.sh
echo 'tmux new-session -d -s sac8 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.8195_t:0.0248_a:0.2_lr:0.004569_hd:256_rbs:10000_bs:256_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:19_r"' >> melco2.sh
echo 'tmux new-session -d -s sac9 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.836_t:0.0464_a:0.2_lr:0.000122_hd:256_rbs:100000_bs:16_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:11_r"' >> melco2.sh
echo 'tmux new-session -d -s sac9 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh
