echo 'SAC_N_CONTROLLER_ABSOLUTE_PATH="/home/taghianj/Documents/server/openai/controllers/sacv2/sacv2_n_controller.py"' > melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant-mehran/data/"' >> melco2.sh
echo 'tmux new-session -d -s sac1 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant-mehran/data/"' >> melco2.sh
echo 'tmux new-session -d -s sac2 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant-mehran/data/"' >> melco2.sh
echo 'tmux new-session -d -s sac3 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant-mehran/data/"' >> melco2.sh
echo 'tmux new-session -d -s sac4 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant-mehran/data/"' >> melco2.sh
echo 'tmux new-session -d -s sac5 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh
