echo 'SAC_N_CONTROLLER_ABSOLUTE_PATH="/home/sschoepp/Documents/openai/controllers/sacv2/sacv2_n_controller.py"' > melco2.sh

# gpu

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9845_t:0.0867_a:0.2_lr:0.000951_hd:256_rbs:100000_bs:64_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:59_r"' >> melco2.sh
echo 'tmux new-session -d -s sac1 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9691_t:0.0455_a:0.2_lr:0.003369_hd:256_rbs:500000_bs:16_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:53_r"' >> melco2.sh
echo 'tmux new-session -d -s sac2 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9646_t:0.0877_a:0.2_lr:0.001092_hd:256_rbs:500000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:61_r"' >> melco2.sh
echo 'tmux new-session -d -s sac3 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9644_t:0.0212_a:0.2_lr:0.000162_hd:256_rbs:10000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:52_r"' >> melco2.sh
echo 'tmux new-session -d -s sac4 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9565_t:0.025_a:0.2_lr:0.003811_hd:256_rbs:500000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:46_r"' >> melco2.sh
echo 'tmux new-session -d -s sac5 "CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed0; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed1; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed2; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed3; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed4; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed5; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed6; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed7; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed8; CUDA_VISIBLE_DEVICES=1 python $SAC_N_CONTROLLER_ABSOLUTE_PATH -c --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh


# cpu

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9462_t:0.0302_a:0.2_lr:0.003405_hd:256_rbs:100000_bs:16_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:98_r"' >> melco2.sh
echo 'tmux new-session -d -s sac6 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.9299_t:0.0879_a:0.2_lr:0.003035_hd:256_rbs:500000_bs:256_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:18_r"' >> melco2.sh
echo 'tmux new-session -d -s sac7 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.8871_t:0.055_a:0.2_lr:0.00016_hd:256_rbs:500000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:2_r"' >> melco2.sh
echo 'tmux new-session -d -s sac8 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh

echo 'RESUME_FILE="/local/melco2-1/shared/ant/SACv2_Ant-v2:20000000_g:0.8588_t:0.0192_a:0.2_lr:0.003186_hd:256_rbs:10000_bs:64_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cpu_ps:True_pss:17_r"' >> melco2.sh
echo 'tmux new-session -d -s sac9 "python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed0; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed1; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed2; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed3; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed4; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed5; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed6; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed7; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed8; python $SAC_N_CONTROLLER_ABSOLUTE_PATH --resume --resume_file $RESUME_FILE/seed9"' >> melco2.sh
