SAC_AB_CONTROLLER_ABSOLUTE_PATH="/home/sschoepp/Documents/openai/controllers/sacv2/sacv2_ab_controller.py"
RESUME_FILE="/local/melco2-1/shared/fetchreach/normal/SACv2_FetchReachEnv-v0:2000000_g:0.8097_t:0.0721_a:0.2_lr:0.001738_hd:256_rbs:10000_bs:512_mups:1_tui:1_tef:10000_ee:10_tmsf:20000_a:True_d:cuda_ps:True_pss:21"
tmux new-session -d -s sac0 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 2000000 -c -f $RESUME_FILE/seed0"
tmux new-session -d -s sac1 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 2000000 -c -f $RESUME_FILE/seed1"
tmux new-session -d -s sac2 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 2000000 -c -f $RESUME_FILE/seed2"
tmux new-session -d -s sac3 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 2000000 -c -f $RESUME_FILE/seed3"
tmux new-session -d -s sac4 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 2000000 -c -f $RESUME_FILE/seed4"
tmux new-session -d -s sac5 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 20000000 -c -f $RESUME_FILE/seed5"
tmux new-session -d -s sac6 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 20000000 -c -f $RESUME_FILE/seed6"
tmux new-session -d -s sac7 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 20000000 -c -f $RESUME_FILE/seed7"
tmux new-session -d -s sac8 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 20000000 -c -f $RESUME_FILE/seed8"
tmux new-session -d -s sac9 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 20000000 -c -f $RESUME_FILE/seed9"
PPO_AB_CONTROLLER_ABSOLUTE_PATH="/home/sschoepp/Documents/openai/controllers/ppov2/ppov2_ab_controller.py"
RESUME_FILE="/local/melco2-1/shared/fetchreach/normal/PPOv2_FetchReachEnv-v0:6000000_lr:0.000275_lrd:True_g:0.848_ns:3424_mbs:8_epo:24_eps:0.3_c1:1.0_c2:0.0007_cvl:False_mgn:0.5_gae:True_lam:0.9327_hd:64_lstd:0.0_tef:30000_ee:10_tmsf:60000_d:cpu_ps:True_pss:43"
tmux new-session -d -s ppov1-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov1cm-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1cm-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm"
tmux new-session -d -s ppov1rn-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1rn-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -rn"
tmux new-session -d -s ppov1cmrn-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov1cmrn-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v1 -t 6000000 -f $RESUME_FILE/seed9 -cm -rn"
tmux new-session -d -s ppov4-0 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-1 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-2 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-3 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-4 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-5 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-6 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-7 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-8 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
tmux new-session -d -s ppov4-9 "python $PPO_AB_CONTROLLER_ABSOLUTE_PATH -e FetchReachEnv-v4 -t 6000000 -f $RESUME_FILE/seed9"
