SAC_AB_CONTROLLER_ABSOLUTE_PATH="/home/taghianj/Documents/openai/controllers/sacv2/sacv2_ab_controller.py"
RESUME_FILE="~/Documents/data_openai/ant/normal/SACv2_Ant-v2:20000000_g:0.9646_t:0.0877_a:0.2_lr:0.001092_hd:256_rbs:500000_bs:512_mups:1_tui:1_tef:100000_ee:10_tmsf:1000000_a:True_d:cuda_ps:True_pss:61_resumed"

#tmux new-session -d -s sacv2-0 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed0 -d"
tmux new-session -d -s sacv2-1 "CUDA_VISIBLE_DEVICES=6 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed1 -d"
#tmux new-session -d -s sacv2-2 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed2 -d"
#tmux new-session -d -s sacv2-3 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed3 -d"
tmux new-session -d -s sacv2-4 "CUDA_VISIBLE_DEVICES=6 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed4 -d"
tmux new-session -d -s sacv2-5 "CUDA_VISIBLE_DEVICES=6 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed5 -d"
tmux new-session -d -s sacv2-6 "CUDA_VISIBLE_DEVICES=7 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed6 -d"
tmux new-session -d -s sacv2-7 "CUDA_VISIBLE_DEVICES=7 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed7 -d"
#tmux new-session -d -s sacv2-8 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed8 -d"
#tmux new-session -d -s sacv2-9 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed9 -d"

#tmux new-session -d -s sacv2_crb-0 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed0 -crb -d"
#tmux new-session -d -s sacv2_crb-1 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed1 -crb -d"
#tmux new-session -d -s sacv2_crb-2 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed2 -crb -d"
#tmux new-session -d -s sacv2_crb-3 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed3 -crb -d"
#tmux new-session -d -s sacv2_crb-4 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed4 -crb -d"
#tmux new-session -d -s sacv2_crb-5 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed5 -crb -d"
#tmux new-session -d -s sacv2_crb-6 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed6 -crb -d"
#tmux new-session -d -s sacv2_crb-7 "CUDA_VISIBLE_DEVICES=0 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed7 -crb -d"
#tmux new-session -d -s sacv2_crb-8 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed8 -crb -d"
#tmux new-session -d -s sacv2_crb-9 "CUDA_VISIBLE_DEVICES=1 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v2 -t 20000000 --resumable -f $RESUME_FILE/seed9 -crb -d"

#tmux new-session -d -s sacv2_antv3_0 "CUDA_VISIBLE_DEVICES=3 python $SAC_AB_CONTROLLER_ABSOLUTE_PATH -c -e AntEnv-v3 -t 20000000 --resumable -f $RESUME_FILE/seed0 -crb -rn"
